"""Add category column to items table

Revision ID: 543bc06c465c
Revises: b8986cda8684
Create Date: 2024-11-01 03:23:11.191800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '543bc06c465c'
down_revision = 'b8986cda8684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
