"""Add category column to items table

Revision ID: 78b9c9f3555c
Revises: cfcac8020299
Create Date: 2024-10-28 18:15:12.488345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78b9c9f3555c'
down_revision = 'cfcac8020299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('credit_limit', sa.Float(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))

    with op.batch_alter_table('premade_box_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    with op.batch_alter_table('premade_boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_items', sa.Integer(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premade_boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('max_items')
        batch_op.drop_column('base_price')

    with op.batch_alter_table('premade_box_items', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('available')
        batch_op.drop_column('category')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('customer_type')

    # ### end Alembic commands ###
