"""Remove price_per_unit column from order_lines

Revision ID: 9f500070c26d
Revises: 543bc06c465c
Create Date: 2024-11-04 12:02:39.403712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f500070c26d'
down_revision = '543bc06c465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
