"""initial schema

Revision ID: db0bd1ca9cd3
Revises: 
Create Date: 2024-11-03 13:30:42.096202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db0bd1ca9cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_column('price_per_unit')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('price_per_unit', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
